### ISSUE TITLE
Test failed with special case

### ISSUE THREAD

**Issue by learning** [seriousManual/dedupe#21]
Special case:
```
it('special case', () => {
    var a = [{a: 1, b: 1}, {a: 2, b: 2}, {a: /3/, b: 3}, {a: '/3/', b: 3}]
    var b = dedupe(a)

    expect(b).to.deep.equal([{a: 1, b: 1}, {a: 2, b: 2}, {a: /3/, b: 3}, {a: '/3/', b: 3}])
})
```

Test failed:
```
  dedupe
    ✓ should remove duplicates
    ✓ should remove multiple duplicates
    ✓ should remove multiple duplicates of multiple values
    ✓ should remove duplicates of complex values
    ✓ should remove duplicates of complex values when using a custom hasher
    1) special case


  5 passing (12ms)
  1 failing

  1) dedupe special case:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(4) ]
      + expected - actual

         {
           "a": /3/
           "b": 3
         }
      +  {
      +    "a": "/3/"
      +    "b": 3
      +  }
       ]

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.it (tests/test.js:45:27)
```

**Comment by seriousManual** [comment]
Hi,
thank you for the issue.

Dedupe uses the sigmund package (https://www.npmjs.com/package/sigmund) underneath to create fast hashes of complex objects. It seems that it uses the stringified version of an RegExp object which incidally was reduced to the exact same string.

You can supply your own hashing function which considers a possible Regexp which string representation is equally to another string thats present.
